import { useState, type FormEvent } from "react";
import { Droplet, Sparkles, Loader2, HelpCircle, Volume2 } from "lucide-react";
import { irrigationAdvice } from "../api/endpoints/publicPortal";
import { Language } from "../types";

interface IrrigationAdviceProps {
  language: Language;
}

const l = (lang: Language, en: string, hi: string, bn: string, te: string) =>
  lang === "hi" ? hi : lang === "bn" ? bn : lang === "te" ? te : en;

const CROPS = ["Rice", "Wheat", "Maize", "Cotton", "Sugarcane"] as const;
const SOILS = ["Alluvial Soil", "Black Soil", "Clayey Soil", "Sandy Soil"] as const;
const STAGES = [
  "Sowing / Seedling",
  "Vegetative Growth",
  "Flowering / Booting",
  "Yield Formation / Grain Filling",
  "Ripening / Maturity",
] as const;
const SOURCES = ["Tube-well", "Canal Irrigation", "Rainfed (No active pump)", "Micro Drip system"] as const;

const CROP_L10N: Record<string, { en: string; hi: string; bn: string; te: string }> = {
  Rice:      { en: "Rice", hi: "धान", bn: "ধান", te: "వరి" },
  Wheat:     { en: "Wheat", hi: "गेहूं", bn: "গম", te: "గోధుమ" },
  Maize:     { en: "Maize", hi: "मक्का", bn: "ভুট্টা", te: "మొక్కజొన్న" },
  Cotton:    { en: "Cotton", hi: "कपास", bn: "তুলা", te: "పత్తి" },
  Sugarcane: { en: "Sugarcane", hi: "गन्ना", bn: "আখ", te: "చెరకు" },
};

const SOIL_L10N: Record<string, { en: string; hi: string; bn: string; te: string }> = {
  "Alluvial Soil": { en: "Alluvial Soil", hi: "गंगा का जलोढ़", bn: "Alluvial Soil", te: "అల్యూవియల్ నేల" },
  "Black Soil":    { en: "Black Soil", hi: "काली मिट्टी", bn: "Black Soil", te: "నల్ల నేల" },
  "Clayey Soil":   { en: "Clayey Soil", hi: "चिकनी मिट्टी", bn: "Clayey Soil", te: "మట్టి నేల" },
  "Sandy Soil":    { en: "Sandy Loam Soil", hi: "बलुई मिट्टी", bn: "Sandy Loam Soil", te: "ఇసుక లోమ్" },
};

const STAGE_L10N: Record<string, { en: string; hi: string; bn: string; te: string }> = {
  "Sowing / Seedling":                { en: "Sowing / Seedling", hi: "बुआई", bn: "Sowing", te: "విత్తడం" },
  "Vegetative Growth":               { en: "Vegetative Growth", hi: "वानस्पतिक विकास", bn: "Vegetative", te: "వృద్ధి దశ" },
  "Flowering / Booting":             { en: "Flowering / Booting", hi: "फूल आना", bn: "Flowering", te: "పుష్ప దశ" },
  "Yield Formation / Grain Filling": { en: "Yield Formation / Grain Filling", hi: "दाना भरना", bn: "Grain Filling", te: "ధాన్యం ఏర్పడటం" },
  "Ripening / Maturity":             { en: "Ripening / Maturity", hi: "फसल पकना", bn: "Ripening", te: "పక్వ దశ" },
};

const SOURCE_L10N: Record<string, { en: string; hi: string; bn: string; te: string }> = {
  "Tube-well":              { en: "Tube-well", hi: "नलकूप", bn: "টিউবওয়েল", te: "ట్యూబ్‌వెల్" },
  "Canal Irrigation":       { en: "Canal Irrigation", hi: "नहर", bn: "খাল", te: "కాలువ" },
  "Rainfed (No active pump)": { en: "Rainfed", hi: "वर्षा आधारित", bn: "বৃষ্টি নির্ভর", te: "వర్షాధారిత" },
  "Micro Drip system":      { en: "Micro Drip System", hi: "टपकन सिंचाई", bn: "ড্রিপ সেচ", te: "డ్రిప్ సిస్టమ్" },
};

export default function IrrigationAdvice({ language }: IrrigationAdviceProps) {
  const [cropName, setCropName] = useState("Rice");
  const [soilType, setSoilType] = useState("Clayey Soil");
  const [stage, setStage] = useState("Vegetative Growth");
  const [source, setSource] = useState("Tube-well");
  const [loading, setLoading] = useState(false);
  const [advice, setAdvice] = useState<string | null>(null);

  const fetchAdvice = async (e: FormEvent) => {
    e.preventDefault();
    setLoading(true);
    try {
      const data = await irrigationAdvice({ cropName, soilType, stage, source, language });
      if (data.success) setAdvice(data.advice);
    } catch (err: unknown) {
      alert(err instanceof Error ? err.message : "Failed to calculate advice");
    } finally {
      setLoading(false);
    }
  };

  const speakAdvice = () => {
    if (!advice) return;
    const utterance = new SpeechSynthesisUtterance(advice);
    utterance.lang = language === "hi" ? "hi-IN" : language === "bn" ? "bn-IN" : language === "te" ? "te-IN" : "en-IN";
    speechSynthesis.speak(utterance);
  };

  const labels = {
    en: {
      title: "Smart Irrigation & Water Advisor",
      sub: "Recommendations are generated by Google Gemini using crop type, soil characteristics, crop growth stage, weather conditions and official agricultural datasets. No custom irrigation prediction model has been trained.",
      crop: "Select Crop Type",
      soil: "Select Soil Type",
      stage: "Current Cultivation Stage",
      source: "Primary Water Source",
      submit: "Calculate Watering Schedule",
      reportTitle: "AI Irrigation Recommendation",
      placeholder: "Click calculate to generate watering guidelines.",
      notice: "AI Reasoning Notice",
    },
    hi: {
      title: "स्मार्ट सिंचाई और जल सलाहकार",
      sub: "फसल प्रकार, मिट्टी की विशेषताओं, फसल विकास चरण, मौसम की स्थिति और आधिकारिक कृषि डेटासेट का उपयोग करके Google Gemini द्वारा सिफारिशें उत्पन्न की जाती हैं। कोई कस्टम सिंचाई पूर्वानुमान मॉडल प्रशिक्षित नहीं किया गया है।",
      crop: "फसल का प्रकार चुनें",
      soil: "मिट्टी का प्रकार चुनें",
      stage: "वर्तमान खेती का चरण",
      source: "प्राथमिक जल स्रोत",
      submit: "सिंचाई कार्यक्रम की गणना करें",
      reportTitle: "एआई सिंचाई सिफ़ारिश",
      placeholder: "पानी देने की दिशा-निर्देश उत्पन्न करने के लिए गणना करें पर क्लिक करें।",
      notice: "एआई तर्क सूचना",
    },
    te: {
      title: "స్మార్ట్ నీటి నిర్వహణ సలహాదారు",
      sub: "పంట రకం, నేల లక్షణాలు, పంట దశ, వాతావరణ పరిస్థితులు మరియు అధికారిక వ్యవసాయ డేటాసెట్ల ఆధారంగా Google Gemini సిఫార్సులను రూపొందిస్తుంది. ఎటువంటి కస్టమ్ నీటి నిర్వహణ మోడల్ శిక్షణ పొందలేదు.",
      crop: "పంటను ఎంచుకోండి",
      soil: "నేల రకాన్ని ఎంచుకోండి",
      stage: "ప్రస్తుత పంట దశ",
      source: "నీటి వనరు",
      submit: "నీటి షెడ్యూల్ పొందండి",
      reportTitle: "AI నీటి నిర్వహణ నివేదిక",
      placeholder: "సూచనలు పొందడానికి 'నీటి షెడ్యూల్ పొందండి' నొక్కండి.",
      notice: "AI హేతుబద్ధత నోటీసు",
    },
    bn: {
      title: "স্মার্ট সেচ এবং জল উপদেষ্টা",
      sub: "ফসলের ধরন, মাটির বৈশিষ্ট্য, ফসলের বৃদ্ধির পর্যায়, আবহাওয়ার অবস্থা এবং অফিসিয়াল কৃষি ডেটাসেট ব্যবহার করে Google Gemini দ্বারা সুপারিশ তৈরি করা হয়। কোনো কাস্টম সেচ পূর্বাভাস মডেল প্রশিক্ষিত হয়নি।",
      crop: "ফসলের ধরন নির্বাচন করুন",
      soil: "মাটির ধরন নির্বাচন করুন",
      stage: "বর্তমান চাষের পর্যায়",
      source: "প্রাথমিক জলের উৎস",
      submit: "সেচ সময়সূচী গণনা করুন",
      reportTitle: "এআই সেচ সুপারিশ",
      placeholder: "সেচ নির্দেশিকা তৈরি করতে গণনা করুন ক্লিক করুন।",
      notice: "এআই যুক্তি বিজ্ঞপ্তি",
    },
  }[language];

  return (
    <div className="space-y-6" id="irrigation-advisory-section">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b-4 border-stone-900 pb-5" id="irrigation-header">
        <div>
          <h2 className="text-2xl font-display font-black text-stone-900 flex items-center gap-2">
            <Droplet className="w-7 h-7 text-emerald-600 animate-bounce" />
            <span>{labels.title}</span>
          </h2>
          <p className="text-stone-500 font-medium text-xs mt-1 max-w-xl">{labels.sub}</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        <form onSubmit={fetchAdvice} className="lg:col-span-5 bg-white border-2 border-stone-900 rounded-3xl p-6 shadow-[4px_4px_0px_0px_rgba(28,25,23,1)] space-y-4" id="irrigation-form">
          <div>
            <label className="block text-xs font-bold text-stone-700 uppercase mb-1.5 font-mono">{labels.crop}</label>
            <select value={cropName} onChange={(e) => setCropName(e.target.value)}
              className="w-full bg-stone-50 border-2 border-stone-900 rounded-xl px-3.5 py-2.5 text-stone-800 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 font-bold">
              {CROPS.map((c) => (
                <option key={c} value={c}>{c} ({CROP_L10N[c][language]})</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold text-stone-700 uppercase mb-1.5 font-mono">{labels.soil}</label>
            <select value={soilType} onChange={(e) => setSoilType(e.target.value)}
              className="w-full bg-stone-50 border-2 border-stone-900 rounded-xl px-3.5 py-2.5 text-stone-800 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 font-bold">
              {SOILS.map((s) => (
                <option key={s} value={s}>{SOIL_L10N[s][language]}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold text-stone-700 uppercase mb-1.5 font-mono">{labels.stage}</label>
            <select value={stage} onChange={(e) => setStage(e.target.value)}
              className="w-full bg-stone-50 border-2 border-stone-900 rounded-xl px-3.5 py-2.5 text-stone-800 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 font-bold">
              {STAGES.map((s) => (
                <option key={s} value={s}>{STAGE_L10N[s][language]}</option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-xs font-bold text-stone-700 uppercase mb-1.5 font-mono">{labels.source}</label>
            <select value={source} onChange={(e) => setSource(e.target.value)}
              className="w-full bg-stone-50 border-2 border-stone-900 rounded-xl px-3.5 py-2.5 text-stone-800 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 font-bold">
              {SOURCES.map((s) => (
                <option key={s} value={s}>{SOURCE_L10N[s][language]}</option>
              ))}
            </select>
          </div>

          <button type="submit" disabled={loading}
            className="w-full bg-emerald-600 hover:bg-emerald-700 disabled:bg-emerald-300 text-white font-display font-black text-sm px-4 py-3 rounded-2xl border-2 border-stone-900 shadow-[2px_2px_0px_0px_rgba(28,25,23,1)] flex items-center justify-center gap-2 transition cursor-pointer mt-2">
            {loading ? (
              <><Loader2 className="w-4 h-4 animate-spin" /><span>Generating AI irrigation recommendation...</span></>
            ) : (
              <><Droplet className="w-4 h-4 text-emerald-200" /><span>{labels.submit}</span></>
            )}
          </button>
        </form>

        <div className="lg:col-span-7 bg-emerald-50 border-2 border-stone-900 rounded-3xl p-6 shadow-[4px_4px_0px_0px_rgba(28,25,23,1)] flex flex-col justify-between" id="irrigation-advisory-display">
          <div>
            <h4 className="font-display font-black text-emerald-900 border-b-2 border-stone-900 pb-3 mb-4 flex items-center gap-2 text-base">
              <Droplet className="w-5 h-5 text-emerald-700" />
              {labels.reportTitle}
            </h4>

            <div className="bg-blue-50 border border-blue-300 rounded-xl p-4 mb-4 text-xs text-blue-900">
              <strong>{labels.notice}</strong>
              <br />
              {labels.sub}
            </div>

            {advice ? (
              <div className="space-y-3">
                <div className="prose prose-stone max-w-none text-stone-800 text-sm whitespace-pre-line leading-relaxed">
                  {advice}
                </div>
                <button onClick={speakAdvice}
                  className="flex items-center gap-2 bg-blue-600 hover:bg-blue-700 text-white font-bold text-xs px-4 py-2 rounded-xl border-2 border-stone-900 shadow-[2px_2px_0px_0px_rgba(28,25,23,1)] transition cursor-pointer">
                  <Volume2 className="w-4 h-4" />
                  Read Aloud
                </button>
              </div>
            ) : (
              <div className="h-64 flex flex-col items-center justify-center text-stone-400 text-center gap-2">
                <HelpCircle className="w-10 h-10 text-stone-300 animate-pulse" />
                <p className="text-sm max-w-xs">{labels.placeholder}</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
